version: '3.8'

services:
  web:
    build: .
    container_name: animale-store
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CI=false
    command: npm run dev 